version: '3'

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        ENVIRONMENT: ${ENVIRONMENT} # customise build for either dev or prod
    ports:
      - "8080:80"
    env_file: .env # load values from .env file
    # environment:
    #   - MYSQL_HOST=mysql
    #   - MYSQL_USER=root
    #   - MYSQL_PASSWORD=rootpassword
    #   - MYSQL_DATABASE=testdb
    #   - MONGO_HOST=mongo
    #   - MONGO_USER=root
    #   - MONGO_PASSWORD=rootpassword
    #   - MONGO_DATABASE=test-mongo-db
    volumes:
      - ./src:/var/www/html  # map host to container volume
    depends_on:
      - mysql
      - mongo

  mysql:
    image: mysql:8.0
    environment:
      - MYSQL_ROOT_PASSWORD=rootpassword
      - MYSQL_DATABASE=testdb

  mongo:
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: rootpassword
